# 1. 简介
在编写Python代码进行自动化测试、网络爬虫或者其他与网络相关的动作的时候，由于网络影响会容易失败，而这种失败并不是我们需要去处理的。那么这种时候最好的办法就是失败后重试几次，以避免网络的间断性影响。

如果我们正常编写代码的话，可能需要 try…except ，但是这种写法很麻烦，能实现的效果也很单一。这里介绍一个 Python 库retrying，专门用来对抛出异常的函数或者方法进行重试。

通过 retrying 你能干什么：

出错后重新运行函数，直到正常运行为止；
出错后，暂停一会再运行函数，因为网络可能一时半会不会好；
出错后，如果重试时间过长，会造成代码效率过低，你可以设置一个最大的重试时间；
出错时，你可能想去执行另一个函数以排除可能的错误。

# 2. 安装

```shell
pip install retrying
```

# 3. 使用

```python
import random
from retrying import retry

def fun():
	# 处理代码
    return True  # => 返回True

@retry(retry_on_result=fun) # 指定函数，如果fun返回True则重试，否则不重试
def demo():
    a = random.randint(1, 2)
    print(a, end=" ")
    if a != 3:
        raise
demo()

```

相关参数

- stop_max_attempt_number 最大重试次数，默认为5次
- ait_fixed 重试的间隔时间， 当函数抛出异常后，
  下一次重试会间隔wait_fixed设置的时间。默认是 1000 毫秒（1秒），
  你可以通过这个参数修改这个默认值。
- wait_random_min 和 wait_random_max 用来设置随机的间隔时间
- wait_random_min 和 wait_random_max 搭配起来设置默认的随机等待时间，默认是 0 ~ 1000 毫秒之间随机等待。
- wait_incrementing_increment 每重试一次，持续增加等待时间，
  默认是 100 毫秒 ，每重试一次，等待时常就会增加 100 毫秒。
- stop_max_delay 最长重试延迟时间，单位毫秒
- retry_on_result：指定一个函数，如果指定的函数返回True，则重试，否则抛出异常退出
- shop_func：指定被装饰函数出错后，会执行的函数，执行该函数后在来重试被装饰的函数。
  注意，该函数必须要有两个参数（attempts, delay）。用来当抛出异常后，
  需要做一些处理的时候

# 参考

[1] Python出错重试：retrying, https://blog.csdn.net/minzhung/article/details/103307080